---
documentclass: article
classoption: a4paper
geometry: "left=1.9cm,right=1.9cm,top=1.78cm,bottom=1.27cm"
output:
  html_document: default
  pdf_document: default
  word_document: default
params:
  address: 'Blk 641B Punggol Dr #10-315 Singapore 822641'
  mobile: '(65) 9129 2887'
  email: 'guanglei.deng@gmail.com'
  github: 'github.com/gldeng'
---


```{r setup, include=FALSE}
options(Encoding="UTF-8")
knitr::opts_chunk$set(echo = TRUE)
library(tools)
```

<style>
@media print {
  a[href]:after {
    content: none !important;
  }
}
body > *{
    width: 17.83cm;
}
table {
    width: 100%;
}
th{
    font-weight: normal;
    text-align: left;
}
td:nth-of-type(1n) {
  text-align: left;
  overflow: hidden;
  text-overflow: ellipsis;
}
td:nth-of-type(2n) {
  text-align: left;
  width: 100%;
}
td:nth-of-type(3n) {
  width: 240px;
  text-align: right;
  overflow: hidden;
  text-overflow: ellipsis;
}
.header{
    display: none;
}
td, th, em{
    white-space: nowrap;
}
.main-info > * {
    display: inline-block;
}
.main-info td:nth-child(n+1) {
    width: 2.53cm;
}
.name h1 {
    display: inline-block;
    -vertical-align: top;
}
.name h1:first-letter {
    font-size: 120%;
}
.name h1::after{
    content: " "
}
.contact {
    text-align: right;
    font-size: 80%;
}
hr {
    margin-top: 0;
}
</style>
<br>

<table class="main-info">
<tr class="name">
<td><h1>DENG</h1><h1>GUANGLEI</h1></td>
<td><span style="display: none;">placeholder</span></td>
<td class="contact">`r params$address`<br>`r params$mobile`<br>`r params$email`<br>`r params$github`</td>
</tr>
</table>
---
### SUMMARY
A Self-Motivated Problem Solver with Excellent Understanding of Computer Science, Outstanding Programming Skills and Great Passion in Quant, Mathematics and Data Science. With broad knowledge scope from Systems to Financial Products and Broader Economics.

### EDUCATION
Year   |Description                 | Institute
-------|----------------------------|-----------
Present| **CFA** Level III Candidate | CFA Institute
2013   | MSc in Applied Economics<br>GPA: 3.97 / 4.0, Dean's List | Singapore Management University
2008   | BEng in Electrical & Electronic Engineering<br>First Class Honours, Full MOE Scholarship, Dean's List | Nanyang Technological University
2004   | Bridging Course for PRC Scholars<br>Top 10%, Accelerated Program |National Institute of Education

### SKILLS
* Python, C#, Scala, C++, Java, Javascript, R, SQL
* Full Stack Development, Software Architecture, Big Data, Data Science

### EXPERIENCES

Year|Title|Company
----|-----|-------
07/2019 to present|**Developer**|Bank of America Merill Lynch

* Analyzed graph database source and developed queries/scripts for sourcing Indonesian entities into local trading system
* Developed scala application for ingesting data from local trading system into Hive data warehouse
* Developed spark rules for data reconciliation
* Modified python scripts for sourcing reference data into Quartz platform

Year|Title|Company
----|-----|-------
04/2018 to 07/2019|**Chief Architect**|Aelf Pte Ltd

* Leading the design, architecting and development of a high-throughput public blockchain project
* Developed a smart contract development and execution platform based on .NET Core and Protobuf
* Developed C++ Protobuf plugin for smart contract generation from proto files
* Developed a Javascript library for dApp to interact with the blockchain
* Developed a C# CLI tool with embedded Javascript engine for interacting with the blockchain
* Performed in-depth research on blockchain core concepts (cryptography, networking and virtual machines, etc.)
* Handling technical matters with partners


Year|Title|Company
----|-----|-------
06/2016 to 04/2018|**Associate, FCC Analytics**|Standard Chartered Bank

* Independently designed and set up Linux infrastructure for handling data generation tasks, analytics and web services (using Python, RQ, Supervisord, Nginx, etc)
* Developed automation scripts in Python
* Developed Python packages for modeling and analyzing various types of transaction messages, customer records and screening alerts
* Developed scripts for data management using multiple formats and/or databases (e.g. csv, json, Parquet, Oracle DB, MongoDB, MonetDB)
* Developed analytics scripts for data analysis and visualization (using pandas, pyarrow, html, D3.js)
* Developed web interfaces for triggering and monitoring server jobs, presenting analysis reports, developing and testing rules (using Flask, AngularJS, etc)
* Helped team to achieve higher productivity by optimizing JIRA workflow and writing scripts for managing JIRA issues and Confluence pages

Year|Title|Company
----|-----|-------
05/2014 to 06/2016|**Software Development Team Lead**|Decision Support Systems Pte. Ltd.

* Developed C++ Interface Application with SGX REACH Trading System for Order Routing and Real-time Market Data Feed
* Developed C# Data Processing Pipeline to Manage Order / Contract / Market Data for Credit Control / Risk Management / Regulatory Compliance
* Designed Reports / Alerts for Real-time Risk Management
* Developed C# Client Application for Data Presentation
* Developed C# Real-time Risk Engine for Automated Risk Management Event Triggering
* Developed Data Collection (e.g. Web Crawler in Python) Scripts to Support Business Analysis
* Developing Data Integrity Tools in Python
* Led Development Team to Implement Data Warehouse System
* Implementing Standard Operation Procedures, Knowledge Management and Team Collaboration Platform
* Devised Strategic Plans for Vertical and Horizontal Business Expansions
* Set Up and Carried Out Plans for Human Resource Development

Year|Title|Company
----|-----|-------
08/2008 to 05/2014|**Sr. Factory Automation Engineer**|GlobalFoundries Singapore Pte. Ltd.

* Analyzed Manufacturing Data to Extract Production Statistics
* Utilized Dataflow Software to Code Logic Rules for Processing Real-time Manufacturing Data to Generate Decisions
* Coded Workflows for Automated Manufacturing Decision Execution
* Carried Out Projects to Boost Factory Automation Level
* Worked on an Innovative Project to Transform Real-time Decision Making into Predicative Decision Making
* Reviewed and Improved Manufacturing Objectives like Product Cycle Time, Equipment Utilization, Product Quality, etc.
* Reviewed and Reduced Execution Time of Critical Data Crunching Rules by 50%
* Developed and Implemented Logistic / Routing Solutions for Fully Automated Material Delivery
* Trained Engineers for New Factory Startup in US

<span style="color: white; font-size: 60%">md5: `r md5sum(knitr::current_input() )`</span>